/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface Quote {
  content: string;
  author: string;
}

export const STUDY_QUOTES: Quote[] = [
  // --- 中国古代儒家及诸子百家经典 (Classic Chinese Philosophies) ---
  { content: "学而时习之，不亦说乎？有朋自远方来，不亦乐乎？", author: "孔子《论语》" },
  { content: "学而不思则罔，思而不学则殆。", author: "孔子《论语》" },
  { content: "温故而知新，可以为师矣。", author: "孔子《论语》" },
  { content: "敏而好学，不耻下问，是以谓之文也。", author: "孔子《论语》" },
  { content: "知之者不如好之者，好之者不如乐之者。", author: "孔子《论语》" },
  { content: "三人行，必有我师焉。择其善者而从之，其不善者而改之。", author: "孔子《论语》" },
  { content: "学如不及，犹恐失之。", author: "孔子《论语》" },
  { content: "锲而舍之，朽木不折；锲而不舍，金石可镂。", author: "荀子《劝学》" },
  { content: "不积跬步，无以至千里；不积小流，无以成江海。", author: "荀子《劝学》" },
  { content: "蓬生麻中，不扶而直；白沙在涅，与之俱黑。", author: "荀子《劝学》" },
  { content: "吾尝终日而思矣，不如须臾之所学也。", author: "荀子《劝学》" },
  { content: "博学之，审问之，慎思之，明辨之，笃行之。", author: "《礼记·中庸》" },
  { content: "玉不琢，不成器；人不学，不知道。", author: "《礼记·学记》" },
  { content: "独学而无友，则孤陋而寡闻。", author: "《礼记·学记》" },
  { content: "善学者，师逸而功倍，又从而庸之。", author: "《礼记·学记》" },
  { content: "天行健，君子以自强不息。", author: "《易经》" },
  { content: "地势坤，君子以厚德载物。", author: "《易经》" },
  { content: "生于忧患而死于安乐也。", author: "孟子《孟子》" },
  { content: "穷则独善其身，达则兼济天下。", author: "孟子《孟子》" },
  { content: "老吾老，以及人之老；幼吾幼，以及人之幼。", author: "孟子《孟子》" },
  { content: "极其自律之人，方得极其自由之翼。", author: "经典自勉格言" },
  { content: "知人者智，自知者明。胜人者有力，自胜者强。", author: "老子《道德经》" },
  { content: "合抱之木，生于毫末；九层之台，起于累土；千里之行，始于足下。", author: "老子《道德经》" },
  { content: "天下难事，必作于易；天下大事，必作于细。", author: "老子《道德经》" },
  { content: "大直若屈，大巧若拙，大辩若讷。静胜躁，寒胜热，清静为天下正。", author: "老子《道德经》" },
  { content: "夫君子之行，静以修身，俭以养德。非淡泊无以明志，非宁静无以致远。", author: "诸葛亮《诫子书》" },
  { content: "淫慢则不能励精，险躁则不能治性。", author: "诸葛亮《诫子书》" },

  // --- 中国唐宋诗词及文人名言 (Tang & Song Dynasties Poetry) ---
  { content: "长风破浪会有时，直挂云帆济沧海。", author: "李白《行路难》" },
  { content: "博观而约取，厚积而薄发。", author: "苏轼《稼说送张忞》" },
  { content: "古之立大事者，不惟有超世之才，亦必有坚忍不拔之志。", author: "苏轼《晁错论》" },
  { content: "旧书不厌百回读，熟读深思子自知。", author: "苏轼《送安惇秀才失意归》" },
  { content: "纸上得来终觉浅，绝知此事要躬行。", author: "陆游《冬夜读书示子聿》" },
  { content: "山重水复疑无路，柳暗花明又一村。", author: "陆游《游山西村》" },
  { content: "少壮不努力，老大徒伤悲。", author: "汉乐府《长歌行》" },
  { content: "三更灯火五更鸡，正是男儿读书时。黑发不知勤学早，白首方悔读书迟。", author: "颜真卿《劝学诗》" },
  { content: "少年易老学难成，一寸光阴不可轻。未觉池塘春草梦，阶前梧叶已秋声。", author: "朱熹《偶成》" },
  { content: "问渠那得清如许？为有源头活水来。", author: "朱熹《观书有感》" },
  { content: "百学须先立志。立志而圣则圣矣，立志而贤则贤矣。", author: "朱熹" },
  { content: "明日复明日，明日何其多。我生待明日，万事成蹉跎。", author: "钱福《明日歌》" },
  { content: "莫等闲、白了少年头，空悲切！", author: "岳飞《满江红》" },
  { content: "业精于勤，荒于嬉；行成于思，毁于随。", author: "韩愈《进学解》" },
  { content: "书山有路勤为径，学海无涯苦作舟。", author: "韩愈《增广贤文》" },
  { content: "穷且益坚，不坠青云之志。", author: "王勃《滕王阁序》" },
  { content: "会当凌绝顶，一览众山小。", author: "杜甫《望岳》" },
  { content: "读书破万卷，下笔如有神。", author: "杜甫《奉赠韦左丞丈二十二韵》" },
  { content: "沉舟侧畔千帆过，病树前头万木春。", author: "刘禹锡《酬乐天扬州初逢席上见赠》" },
  { content: "千淘万漉虽辛苦，吹尽狂沙始到金。", author: "刘禹锡《浪淘沙》" },
  { content: "不畏浮云遮望眼，自缘身在最高层。", author: "王安石《登飞来峰》" },
  { content: "劝君莫惜金缕衣，劝君惜取少年时。", author: "杜秋娘《金缕衣》" },
  { content: "欲穷千里目，更上一层楼。", author: "王之涣《登鹳雀楼》" },
  { content: "有毅力者成，无毅力者败。在自律中重塑生命的内核。", author: "梁启超" },
  { content: "少年智则国智，少年富则国富，少年强则国强。", author: "梁启超《少年中国说》" },
  { content: "读书百遍，其义自见。", author: "陈寿《三国志》" },
  { content: "学所以益才也，砺所以致刃也。", author: "刘向《说苑》" },
  { content: "绳锯木断，水滴石穿。锲而不舍的努力能战胜任何天资不足。", author: "罗贯中《三国演义》" },
  { content: "宝剑锋从磨砺出，梅花香自苦寒来。", author: "《警世贤文》" },
  { content: "一寸光阴一寸金，寸金难买寸光阴。", author: "王贞白《白鹿洞二首》" },
  { content: "不飞则已，一飞冲天；不鸣则已，一鸣惊人。", author: "《史记·滑稽列传》" },
  { content: "非学无以广才，非志无以成学。", author: "诸葛亮" },
  { content: "路漫漫其修远兮，吾将上下而求索。", author: "屈原《离骚》" },

  // --- 近现代中国学者及自省自律格言 (Modern Chinese Scholars & Aphorisms) ---
  { content: "最可怕的敌人，就是自己没有坚定的信念与自控的力量。", author: "鲁迅" },
  { content: "唯有坚持不懈的人，才能在无人问津的泥淖里绽放成繁花。", author: "鲁迅" },
  { content: "哪里有天才，我是把别人喝咖啡的工夫都用在工作上的。", author: "鲁迅" },
  { content: "学问是苦根上长出来的甜果。", author: "现代教育家格言" },
  { content: "自律是一场修行，它的终点不是限制自由，而是获得纯粹的自由。", author: "著名自省格言" },
  { content: "天下无难事，只怕有心人。有心之人，必深谙自律之道。", author: "《格言联璧》" },
  { content: "心懒则百事废，心勤则万象新。随时省察，不令懈怠。", author: "曾国藩《曾国藩家书》" },
  { content: "大处着眼，小处着手；群居守口，独居守心。自律当从细微起。", author: "曾国藩" },
  { content: "千古第一完人，其秘诀唯在于‘恒’。坚持，就是最伟大的天资。", author: "曾国藩" },
  { content: "每一个看似平凡的微小努力，都在暗地里雕刻着你的未来面貌。", author: "近现代自学者信条" },
  { content: "读书，是人生中最便宜、最高级的越级跨阶武器。", author: "自勉格言" },
  { content: "自省是心灵的镜子，自律是行动的锁匙。无此二者，学问终是虚妄。", author: "《格言联璧》" },

  // --- 西方哲学、科学及思想家名言 (Western Philosophy, Science & Thinkers) ---
  { content: "生命的意义在于坚持不懈地追求那些更崇高的事物，哪怕路途遥远。", author: "苏格拉底 (Socrates)" },
  { content: "未经审视的人生，是不值得过的。", author: "苏格拉底 (Socrates)" },
  { content: "卓越不是一种行为，而是一种习惯。我们之所以卓越，是因为我们反复坚持。", author: "亚里士多德 (Aristotle)" },
  { content: "知识的唯一源泉是经验。最好的学习，莫过于深度实践与复盘。", author: "爱因斯坦 (Albert Einstein)" },
  { content: "不要试图去做一个成功的人，要努力去做一个有价值的人。", author: "爱因斯坦 (Albert Einstein)" },
  { content: "你必须在生命中持守一些极其纯粹的目标，这就是最好的自律。", author: "康德 (Immanuel Kant)" },
  { content: "所谓自由，不是随心所欲，而是自我主宰。无法自制的人无以谈自由。", author: "康德 (Immanuel Kant)" },
  { content: "每一个不曾起舞的日子，都是对生命的辜负。", author: "尼采 (Friedrich Nietzsche)" },
  { content: "谁终将声震人间，必长久深自缄默；谁终将点燃闪电，必长久如云漂泊。", author: "尼采 (Friedrich Nietzsche)" },
  { content: "人不能两次踏进同一条河流。唯有保持变中求稳、终身学习，方能掌舵。", author: "赫拉克利特 (Heraclitus)" },
  { content: "幸运更垂青于那些有准备、勤自律的心灵。", author: "路易斯·巴斯德 (Louis Pasteur)" },
  { content: "最强大的人，是那些能够战胜自己欲望并牢牢掌控自己行为的人。", author: "塞涅卡 (Seneca)" },
  { content: "自律就是力量。它能将无序的情感化作雷霆万钧的行动力。", author: "塞涅卡 (Seneca)" },
  { content: "伟大的工作并非依靠力量完成，而是依靠惊人的恒心与自律。", author: "塞缪尔·约翰逊 (Samuel Johnson)" },
  { content: "如果你不比昨天更博学，那么你就虚度了今天的阳光。", author: "约翰·洛克 (John Locke)" },
  { content: "控制我们的注意力，就是控制我们真正的生命主权。", author: "威廉·詹姆斯 (William James)" },
  { content: "克服拖延的最好秘诀：就是立刻、欢快地迈出那极其微小的一步。", author: "威廉·詹姆斯" },
  { content: "没有一艘远洋轮船能像一本书籍那样，带我们畅游人间美景。", author: "艾米莉·狄金森 (Emily Dickinson)" },
  { content: "知识就是力量，而自律则是让力量精准落地的准绳。", author: "弗朗西斯·培根 (Francis Bacon)" },
  { content: "读书能塑造心灵。正如运动之于身体，阅读与静思之于大脑亦是如此。", author: "约瑟夫·艾迪生 (Joseph Addison)" },
  { content: "不要为失去的时间叹息，而要为可控制的当下而欢欣鼓舞。", author: "歌德 (Johann Wolfgang von Goethe)" },
  { content: "思考是容易的，行动是困难的，而将想法付诸自律的行动是世上最难的事。", author: "歌德 (Johann Wolfgang von Goethe)" },
  { content: "那些最杰出的人物之所以伟大，是因为他们深谙精力的分配与专注。", author: "叔本华 (Arthur Schopenhauer)" },
  { content: "自律带来尊严，自律带来专注，自律将平庸的生活熬制成高奢的艺术。", author: "罗曼·罗兰 (Romain Rolland)" },
  { content: "如果你足够坚韧，时间定会站在你这一边，为你酿出最甜的酒。", author: "罗曼·罗兰 (Romain Rolland)" },
  { content: "我的精力只集中于当下要做的一件事。分心是所有心智低下的根源。", author: "牛顿 (Sir Isaac Newton)" },
  { content: "如果说我看得比别人更远些，那是因为我站在巨人的肩膀上。", author: "牛顿 (Sir Isaac Newton)" },
  { content: "不要等待机会，要用坚实的、日复一日的细节去创造机会。", author: "马克·吐温 (Mark Twain)" },
  { content: "保持专注是通往天才的唯一桥梁。一旦专注成为习惯，奇迹便随之产生。", author: "达芬奇 (Leonardo da Vinci)" },
  { content: "一个人能够掌控自己的时间和专注力，就能掌控自己的大半生。", author: "经典效率格言" },
  { content: "所谓天才，就是长期的坚持、高频的自省与不可摧毁的自律品质。", author: "经典成长格言" },
  { content: "真正的平静，不是逃避车马喧嚣，而是在内心里建立强大的专注秩序。", author: "经典正念自勉" }
];
